export type RegisterFormCopy = {
  registerTitle: string
  registerSubtitle: string
  registerFullNameLabel: string
  registerFullNamePlaceholder: string
  registerEmailLabel: string
  registerEmailPlaceholder: string
  continue: string
  back: string
  otpTitle: string
  otpSubtitle: string
  otpConfirm: string
  otpResendIn: string
  otpResend: string
  companyTitle: string
  companySubtitle: string
  companyNameLabel: string
  companyNamePlaceholder: string
  companyAddressLabel: string
  companyAddressPlaceholder: string
  companyPhoneLabel: string
  companyLicenseLabel: string
  companyCertificateLabel: string
  createPasswordTitle: string
  createPasswordBody: string
  passwordLabel: string
  passwordPlaceholder: string
  confirmPasswordLabel: string
  registerSuccessToast: string
  registerErrorToast: string
  validationFullNameRequired: string
  validationEmailRequired: string
  validationEmailInvalid: string
  validationCompanyNameRequired: string
  validationAddressRequired: string
  validationPhoneRequired: string
  validationPhoneInvalid: string
  validationPasswordRequired: string
  validationConfirmPasswordRequired: string
  validationPasswordsMismatch: string
  conditionsTitle: string
  conditionsAgreement: string
  conditionsSubmit: string
  requestSentTitle: string
  requestSentBody: string
  requestSentSupportPrefix: string
}
